### ISSUE TITLE
can't rebuild system due to lack of kernel sandboxing

### ISSUE THREAD

**Issue by zarkone** [tfc/nspawn-nixos#5]
after getting system running inside of container, I've adjusted the configuration of "configuration.nix" and tried to rebuild the system:

```
$ nixos-rebuild switch
error: this system does not support the kernel namespaces that are required for sandboxing; use '--no-sandbox' to disable sandboxing
```

not sure if I'm missing something obvious here..?

**Comment by chuck-r** [comment]
I started trying to use NixOS about a year ago and ran into this roadblock as well. Sure, I can run it in a VM, but I want to use a container because it has fewer resource requirements. This roadblock caused me to give up NixOS entirely until this week. And, here I am again at this dead end. As a temporary fix, you can add the following to your /etc/nixos/configuration.nix:

````
nix.settings.use-sandbox = false;
````

However, I have no idea what the ramifications of that change are.

**Comment by zarkone** [comment]
thanks @chuck-r ! will check this out :+1:

**Comment by srd424** [comment]
I think this is an instance of the bug I've just reported against nix: https://github.com/NixOS/nix/issues/13128 - I've posted a more elaborate work-around in there.
